@startuml

title __BEAN's Class Diagram__\n

  namespace Bean {
    class Bean.DMFoodBeaan {
        - effect : String
        - heat : String
        - image : String
        - name : String
        + getEffect()
        + getHeat()
        + getImage()
        + getName()
        + setEffect()
        + setHeat()
        + setImage()
        + setName()
        + toString()
    }
  }
  

  namespace Bean {
    class Bean.DaynotesBean {
        - content : String
        - name : String
        + DaynotesBean()
        + getContent()
        + getName()
        + setContent()
        + setName()
        + toString()
    }
  }
  

  namespace Bean {
    class Bean.FoodBean {
        - cho : String
        - e460 : String
        - fat : String
        - heat : String
        - image : String
        - name : String
        - pro : String
        + getCho()
        + getE460()
        + getFat()
        + getHeat()
        + getImage()
        + getName()
        + getPro()
        + setCho()
        + setE460()
        + setFat()
        + setHeat()
        + setImage()
        + setName()
        + setPro()
        + toString()
    }
  }
  

  namespace Bean {
    class Bean.RecommendBean {
        - desc : String
        - image : int
        + getDesc()
        + getImage()
        + setDesc()
        + setImage()
        + toString()
    }
  }
  

  namespace Bean {
    class Bean.SingleFoodBean {
        - cho : String
        - e460 : String
        - fat : String
        - heat : String
        - image : String
        - name : String
        - pro : String
        + getCho()
        + getE460()
        + getFat()
        + getHeat()
        + getImage()
        + getName()
        + getPro()
        + setCho()
        + setE460()
        + setFat()
        + setHeat()
        + setImage()
        + setName()
        + setPro()
        + toString()
    }
  }
  

  namespace Bean {
    class Bean.UserAccountBean {
        - password : String
        - userid : String
        - username : String
        + getPassword()
        + getUserid()
        + getUsername()
        + setPassword()
        + setUserid()
        + setUsername()
        + toString()
    }
  }
  

  namespace Bean {
    class Bean.WeekNotesBean {
        - day : String
        - daynotesBeanList : List<DaynotesBean>
        + WeekNotesBean()
        + getDay()
        + getDaynotesBeanList()
        + setDay()
        + setDaynotesBeanList()
        + toString()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
